import './global.css';
import { ThemeProvider } from '../containers/context/theme-context';
import { AppProviders } from '../containers/context/providers';

export const metadata = {
  title: 'Welcome to paralympics-2024',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AppProviders>{children}</AppProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
